# backend-deployment.yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: backend
     namespace: edu-ai-system
   spec:
     replicas: 2
     selector:
       matchLabels:
         app: backend
     template:
       metadata:
         labels:
           app: backend
       spec:
         containers:
         - name: backend
           image: your-registry/edu-ai-backend:latest
           ports:
           - containerPort: 8000
           env:
           - name: DATABASE_URL
             value: "mysql+pymysql://root:$(DB_ROOT_PASSWORD)@mariadb:3306/edu_ai_db"
           - name: CELERY_BROKER_URL
             value: "redis://redis:6379/0"
           - name: SECRET_KEY
             valueFrom:
               secretKeyRef:
                 name: backend-secret
                 key: secret-key
           volumeMounts:
           - name: nas-models
             mountPath: /mnt/nas/models
         volumes:
         - name: nas-models
           persistentVolumeClaim:
             claimName: nas-models-pvc
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: backend-service
     namespace: edu-ai-system
   spec:
     selector:
       app: backend
     ports:
     - port: 8000