# mariadb-deployment.yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: mariadb
     namespace: edu-ai-system
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: mariadb
     template:
       metadata:
         labels:
           app: mariadb
       spec:
         containers:
         - name: mariadb
           image: mariadb:10.6
           ports:
           - containerPort: 3306
           env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mariadb-secret
                 key: root-password
           - name: MYSQL_DATABASE
             value: edu_ai_db
           volumeMounts:
           - name: mariadb-data
             mountPath: /var/lib/mysql
           - name: config
             mountPath: /etc/mysql/conf.d
         volumes:
         - name: mariadb-data
           persistentVolumeClaim:
             claimName: mariadb-pvc
         - name: config
           configMap:
             name: mariadb-config
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: mariadb
     namespace: edu-ai-system
   spec:
     selector:
       app: mariadb
     ports:
     - port: 3306
       clusterIP: None