# mariadb-configmap.yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: mariadb-config
     namespace: edu-ai-system
   data:
     my.cnf: |
       [mysqld]
       character-set-server=utf8mb4
       collation-server=utf8mb4_unicode_ci
       max_allowed_packet=256M